Repository eth-cscs/DLA-Future, pull requests merged in 2022-12, with the labels that each got.

#718 algo: applyGivenRotations Distributed (GPU)
  include/dlaf/eigensolver/tridiag_solver/rot.h
  test/unit/eigensolver/CMakeLists.txt
  test/unit/eigensolver/test_tridiag_solver_rot.cpp
Labels: RTMWTP, Priority:Medium

#692 Adapt tridiag eigensolver to hip
  CMakeLists.txt
  ci/.gitlab-ci.yml
  ci/docker/amdgpu-release-rocm523.yaml
  cmake/template/DLAFConfig.cmake.in
  include/dlaf/eigensolver/tridiag_solver.h
  include/dlaf/gpu/blas/api.h
  include/dlaf/gpu/cub/api.h
  miniapp/CMakeLists.txt
  spack/packages/dla-future/package.py
  src/CMakeLists.txt
  src/eigensolver/tridiag_solver/kernels.cu
  test/unit/eigensolver/test_eigensolver.cpp
  test/unit/eigensolver/test_gen_eigensolver.cpp
Labels: Priority:Medium

#678 Use ci-ext
  README.md
  bors.toml
  ci/.gitlab-ci.yml
  ci/docker/build.Dockerfile
  ci/docker/codecov.Dockerfile
  ci/docker/deploy-amdgpu.Dockerfile
  ci/docker/deploy.Dockerfile
  ci/set_github_status.sh
Labels: CI, Priority:Low

#722 Prepend paths to `CMAKE_MODULE_PATH` to make sure DLA-Future's own `Find` modules take precedence
  CMakeLists.txt
  cmake/template/DLAFConfig.cmake.in
Labels: bug, Priority:Low

#743 Enable warnings as error for all languages
  include/dlaf/gpu/cub/api.h
  spack/packages/dla-future/package.py
  src/cusolver/stedc.cu
  src/eigensolver/tridiag_solver/kernels.cu
Labels: RTMWTP

#706 Always compress debug symbols
  cmake/DLAF_AddMiniapp.cmake
  cmake/DLAF_AddTest.cmake
  src/CMakeLists.txt
Labels: RTMWTP, Priority:Low

#742 Update rocm CI runs to target hohgant.
  ci/.gitlab-ci.yml
  ci/docker/codecov.Dockerfile
  ci/docker/debug-cpu.yaml
  ci/docker/debug-cuda.yaml
  ci/docker/deploy-amdgpu.Dockerfile
  ci/docker/deploy.Dockerfile
  ci/docker/release-cpu.yaml
  ci/docker/release-cuda.yaml
  ci/docker/release-rocm523.yaml
  ci/run_amd_gpu.sh
Labels: CI, Priority:Low

#674 Reduce debug bloat part 2
  include/dlaf/communication/broadcast_panel.h
  include/dlaf/communication/kernels/all_reduce.h
  include/dlaf/communication/kernels/broadcast.h
  include/dlaf/communication/kernels/p2p.h
  include/dlaf/communication/kernels/p2p_allsum.h
  include/dlaf/communication/kernels/reduce.h
  include/dlaf/eigensolver/band_to_tridiag/mc.h
  include/dlaf/eigensolver/bt_band_to_tridiag/impl.h
  include/dlaf/eigensolver/bt_reduction_to_band/impl.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/eigensolver/tridiag_solver/rot.h
  include/dlaf/sender/traits.h
  include/dlaf/solver/triangular/impl.h
  src/CMakeLists.txt
  src/communication/kernels/all_reduce.cpp
  src/communication/kernels/broadcast.cpp
  src/communication/kernels/p2p.cpp
  src/communication/kernels/reduce.cpp
  test/unit/auxiliary/mc/CMakeLists.txt
  test/unit/communication/CMakeLists.txt
  test/unit/communication/test_collective_async.cpp
  test/unit/communication/test_comm_matrix.cpp
  test/unit/communication/test_comm_p2p.cpp
  test/unit/eigensolver/CMakeLists.txt
  test/unit/eigensolver/test_tridiag_solver_distributed.cpp
  test/unit/factorization/CMakeLists.txt
  test/unit/permutations/CMakeLists.txt
Labels: Priority:Medium

#738 Update pika to 0.11.0
  CMakeLists.txt
  ci/.gitlab-ci.yml
  spack/packages/dla-future/package.py
  src/CMakeLists.txt
Labels: Priority:Low

#748 Don't include algorithm implementations in public headers
  include/dlaf/eigensolver/bt_reduction_to_band.h
  include/dlaf/eigensolver/bt_reduction_to_band/api.h
  include/dlaf/eigensolver/gen_to_std.h
  include/dlaf/eigensolver/gen_to_std/api.h
  include/dlaf/eigensolver/reduction_to_band.h
  include/dlaf/eigensolver/reduction_to_band/api.h
  include/dlaf/eigensolver/tridiag_solver.h
  include/dlaf/factorization/qr.h
  include/dlaf/factorization/qr/api.h
  src/eigensolver/bt_reduction_to_band/gpu.cpp
  src/eigensolver/bt_reduction_to_band/mc.cpp
  src/eigensolver/reduction_to_band/gpu.cpp
  src/eigensolver/reduction_to_band/mc.cpp
  src/factorization/qr/gpu.cpp
  src/factorization/qr/mc.cpp
  test/unit/eigensolver/test_tridiag_solver_distributed.cpp
  test/unit/eigensolver/test_tridiag_solver_local.cpp
Labels: Priority:Low

#658 Remove explicit use of futures in tridiagonal solver
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/eigensolver/tridiag_solver/kernels.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/util_matrix.h
  test/unit/eigensolver/test_tridiag_solver_merge.cpp
Labels: Priority:Low

#749 Add support to all miniapps in plotting scripts
  miniapp/miniapp_band_to_tridiag.cpp
  miniapp/miniapp_bt_band_to_tridiag.cpp
  scripts/gen_dlaf_strong.py
  scripts/gen_dlaf_weak.py
  scripts/miniapps.py
  scripts/plot_band2trid_strong.py
  scripts/plot_band2trid_weak.py
  scripts/plot_bt_band2trid_strong.py
  scripts/plot_bt_band2trid_weak.py
  scripts/plot_evp_strong.py
  scripts/plot_evp_weak.py
  scripts/plot_gevp_strong.py
  scripts/plot_gevp_weak.py
  scripts/plot_red2band_strong.py
  scripts/plot_red2band_weak.py
  scripts/postprocess.py
Labels: Priority:High

#751 Fix codecov: remove old gitlab mirror repo and keep only github, change badge to point to github badge
  README.md
  ci/upload_codecov
Labels: CI, Priority:High

#724 Panel StoreTransposed
  include/dlaf/common/index2d.h
  include/dlaf/communication/broadcast_panel.h
  include/dlaf/matrix/panel.h
  include/dlaf/util_matrix.h
  test/unit/communication/test_broadcast_panel.cpp
  test/unit/matrix/test_matrix.cpp
  test/unit/matrix/test_panel.cpp
Labels: Priority:Medium

#725 Panel StoreTranposed adaptations to algorithms
  include/dlaf/eigensolver/gen_to_std/impl.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
  include/dlaf/factorization/cholesky/impl.h
Labels: Priority:Medium, Priority:on hold

#753 Add miniapp for tridiagonal eigensolver (and plotting facilities)
  miniapp/CMakeLists.txt
  miniapp/miniapp_tridiag_solver.cpp
  scripts/gen_dlaf_strong.py
  scripts/gen_dlaf_weak.py
  scripts/miniapps.py
  scripts/plot_tridiag_solver_strong.py
  scripts/plot_tridiag_solver_weak.py
  scripts/postprocess.py
  scripts/requirements.txt
  test/unit/eigensolver/test_tridiag_solver_distributed.cpp
  test/unit/eigensolver/test_tridiag_solver_local.cpp
Labels: Priority:Medium

#726 algo: enable sub-band in ReductionToBand Distributed (both MC and GPU)
  include/dlaf/eigensolver/eigensolver/impl.h
  include/dlaf/eigensolver/reduction_to_band.h
  include/dlaf/eigensolver/reduction_to_band/api.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
  include/dlaf/matrix/panel.h
  miniapp/miniapp_reduction_to_band.cpp
  test/unit/eigensolver/test_reduction_to_band.cpp
Labels: Priority:Medium
