Repository eth-cscs/DLA-Future, pull requests merged in 2022-11, with the labels that each got.

#689 Pass the `amdgpu_target` and `cuda_arch` variants to DLAF dependencies
  spack/packages/dla-future/package.py
Labels: CI

#703 Enable gpu backend for tridiagonal eigensolver
  include/dlaf/eigensolver/eigensolver/impl.h
  miniapp/CMakeLists.txt
  test/unit/eigensolver/test_eigensolver.cpp
  test/unit/eigensolver/test_gen_eigensolver.cpp
Labels: Priority:High

#695 Port to pika 0.10.0
  ci/.gitlab-ci.yml
Labels: Priority:Low

#705 Add shared libraries variant to spack package and enable it by default
  CMakeLists.txt
  include/dlaf/eigensolver/tridiag_solver.h
  spack/packages/dla-future/package.py
Labels: bug, RTMWTP, Urgent, CI

#683 algo: Reduction to band Distributed GPU
  include/dlaf/eigensolver/reduction_to_band.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
  include/dlaf/matrix/matrix.h
  include/dlaf/matrix/panel.h
  src/eigensolver/reduction_to_band/gpu.cpp
  test/unit/eigensolver/test_reduction_to_band.cpp
Labels: RTMWTP, Priority:Medium

#675 algo: applyGivenRotations Distributed (MC)
  include/dlaf/communication/kernels/p2p.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/eigensolver/tridiag_solver/rot.h
  include/dlaf/matrix/distribution.h
  include/dlaf/permutations/general/impl.h
  include/dlaf/util_matrix.h
  test/unit/eigensolver/CMakeLists.txt
  test/unit/eigensolver/test_tridiag_solver_rot.cpp
Labels: Priority:High

#714 Make sure split communicators in `CommunicatorGrid6RanksEnvironment` are freed by making them managed
  test/include/dlaf_test/comm_grids/grids_6_ranks.h
Labels: bug, Priority:Low

#716 More build dependencies from apt-get
  ci/docker/amdgpu-release-rocm523.yaml
  ci/docker/build.Dockerfile
  ci/docker/cpu-debug.yaml
  ci/docker/cpu-release.yaml
  ci/docker/gpu-debug.yaml
  ci/docker/gpu-release.yaml
Labels: CI, Priority:Low

#721 Fix requirement mismatch in applyGivenRotations (and improve doc)
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/eigensolver/tridiag_solver/rot.h
  test/unit/eigensolver/test_tridiag_solver_rot.cpp
Labels: bug, Priority:High

#713 bandtotridiagonal from GPU memory
  include/dlaf/eigensolver/band_to_tridiag.h
  include/dlaf/eigensolver/band_to_tridiag/api.h
  include/dlaf/eigensolver/band_to_tridiag/mc.h
  include/dlaf/sender/traits.h
  src/eigensolver/band_to_tridiag/mc.cpp
  test/unit/eigensolver/test_band_to_tridiag.cpp
Labels: Priority:Medium

#719 Distributed tridiagonal solver (MC)
  include/dlaf/eigensolver/tridiag_solver.h
  include/dlaf/eigensolver/tridiag_solver/api.h
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/eigensolver/tridiag_solver/kernels.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/eigensolver/tridiag_solver/rot.h
  include/dlaf/eigensolver/tridiag_solver/tile_collector.h
  include/dlaf/matrix/distribution.h
  include/dlaf/multiplication/general.h
  include/dlaf/multiplication/general/api.h
  include/dlaf/multiplication/general/impl.h
  include/dlaf/permutations/general.h
  include/dlaf/permutations/general/api.h
  include/dlaf/permutations/general/impl.h
  src/eigensolver/tridiag_solver/kernels.cpp
  src/eigensolver/tridiag_solver/kernels.cu
  test/unit/eigensolver/CMakeLists.txt
  test/unit/eigensolver/test_tridiag_solver_distributed.cpp
  test/unit/eigensolver/test_tridiag_solver_local.cpp
  test/unit/eigensolver/test_tridiag_solver_merge.cpp
  test/unit/permutations/test_permutations_distributed.cpp
Labels: Priority:High
