Repository eth-cscs/DLA-Future, pull requests merged in 2022-10, with the labels that each got.

#633 algo: Backtransformation from Tridiagonal to Band (Distributed, both MC and GPU)
  include/dlaf/eigensolver/bt_band_to_tridiag.h
  include/dlaf/eigensolver/bt_band_to_tridiag/api.h
  include/dlaf/eigensolver/bt_band_to_tridiag/impl.h
  include/dlaf/matrix/print_gpu.h
  src/eigensolver/bt_band_to_tridiag/gpu.cpp
  src/eigensolver/bt_band_to_tridiag/mc.cpp
  test/unit/eigensolver/CMakeLists.txt
  test/unit/eigensolver/test_bt_band_to_tridiag.cpp
Labels: Priority:High

#673 Fix condition for adding `CMAKE_HIP_ARCHITECTURES` in spack package
  spack/packages/dla-future/package.py
Labels: Priority:Medium

#670 Make DLA-Future install/build verbose in CI
  ci/ctest_to_gitlab.sh
  ci/docker/codecov.Dockerfile
  ci/docker/deploy-amdgpu.Dockerfile
  ci/docker/deploy.Dockerfile
Labels: Priority:Medium

#659 algo: Distributed sub-Gemm (trisolver use-case)
  include/dlaf/multiplication/general.h
  include/dlaf/multiplication/general/api.h
  include/dlaf/multiplication/general/impl.h
  src/multiplication/general/mc.cpp
  test/include/dlaf_test/matrix/util_generic_blas.h
  test/include/dlaf_test/util_types.h
  test/unit/multiplication/CMakeLists.txt
  test/unit/multiplication/test_multiplication_general.cpp
Labels: Priority:High

#639 Use whip instead of macros for HIP/CUDA compatibility
  CMakeLists.txt
  cmake/template/DLAFConfig.cmake.in
  include/dlaf/blas/tile.h
  include/dlaf/eigensolver/band_to_tridiag/mc.h
  include/dlaf/eigensolver/bt_band_to_tridiag/impl.h
  include/dlaf/eigensolver/bt_reduction_to_band/impl.h
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/eigensolver/tridiag_solver/kernels.h
  include/dlaf/factorization/qr/t_factor_impl.h
  include/dlaf/gpu/api.h
  include/dlaf/gpu/assert.cu.h
  include/dlaf/gpu/error.h
  include/dlaf/gpu/lapack/assert_info.h
  include/dlaf/lapack/gpu/lacpy.h
  include/dlaf/lapack/gpu/laset.h
  include/dlaf/lapack/tile.h
  include/dlaf/matrix/copy_tile.h
  include/dlaf/matrix/print_gpu.h
  include/dlaf/memory/memory_chunk.h
  include/dlaf/permutations/general/perms.h
  include/dlaf/sender/transform.h
  miniapp/include/dlaf/miniapp/kernel_runner.h
  miniapp/kernel/miniapp_laset.cpp
  spack/packages/dla-future/package.py
  src/CMakeLists.txt
  src/cusolver/assert_info.cu
  src/cusolver/stedc.cu
  src/eigensolver/tridiag_solver/kernels.cu
  src/lapack/gpu/lacpy.cu
  src/lapack/gpu/laset.cu
  src/permutations/general/perms.cu
  test/include/dlaf_test/blas/invoke.h
  test/include/dlaf_test/lapack/invoke.h
  test/unit/lapack/gpu/test_lacpy.cpp
  test/unit/test_util_cuda.cu
Labels: Task

#660 Try to avoid fetch errors in spack CI
  ci/docker/build.Dockerfile
Labels: CI

#682 algo: BackTransformation Band Distributed GPU (and computeTFactor)
  include/dlaf/communication/kernels/all_reduce.h
  include/dlaf/eigensolver/bt_reduction_to_band/impl.h
  include/dlaf/factorization/qr/t_factor_impl.h
  test/unit/eigensolver/test_bt_reduction_to_band.cpp
  test/unit/factorization/test_compute_t_factor.cpp
Labels: Priority:High

#691 Fix band to tridiagonal backtransformation
  include/dlaf/eigensolver/bt_band_to_tridiag/impl.h
Labels: RTMWTP
