Repository eth-cscs/DLA-Future, pull requests merged in 2023-11, with the labels that each got.

#1027 Fix build problem with clang due to nested structure definition
  ci/.gitlab-ci.yml
  ci/cpu/clang15_release.yml
  ci/docker/release-cpu-serial.yaml
  include/dlaf/eigensolver/tridiag_solver/merge.h
Labels: Type:Problem

#1032 Fix CI configurations
  ci/.gitlab-ci.yml
  ci/cpu/clang12_release_stdexec.yml
  ci/cpu/clang14_release_stdexec.yml
  ci/cpu/clang15_release.yml
  ci/docker/build.Dockerfile
  ci/rocm/clang14_release_stdexec.yml
Labels: Type:Bug, Category:CI, Priority:High

#1031 Add placeholder for v0.3.0 doc and update Readme
  README.md
Labels: Category:Documentation, Priority:High, Type:Release

#1034 Update package after v0.3.0 release
  ci/common-ci.yml
  ci/docker/build.Dockerfile
  ci/docker/debug-cpu-stdexec.yaml
  ci/docker/debug-cpu.yaml
  ci/docker/debug-cuda-scalapack.yaml
  ci/docker/debug-cuda.yaml
  ci/docker/release-cpu-serial.yaml
  ci/docker/release-cpu-stdexec.yaml
  ci/docker/release-cpu.yaml
  ci/docker/release-cuda-scalapack.yaml
  ci/docker/release-cuda.yaml
  ci/docker/release-rocm533-stdexec.yaml
  ci/docker/release-rocm533.yaml
  spack/packages/dla-future/package.py
Labels: Priority:High, Type:Release

#1007 First matrix cleanup
  include/dlaf/matrix/create_matrix.h
  include/dlaf/matrix/distribution.h
  include/dlaf/matrix/matrix.h
  include/dlaf/matrix/matrix.tpp
  include/dlaf/matrix/matrix_base.h
  include/dlaf/matrix/matrix_const.tpp
  include/dlaf/util_matrix.h
  src/c_api/eigensolver/eigensolver.h
  src/c_api/eigensolver/gen_eigensolver.h
  test/include/dlaf_test/matrix/matrix_local.h
  test/unit/matrix/test_matrix.cpp
Labels: Priority:Medium, Type:Cleanup

#1039 Improve eigensolver tests
  include/dlaf/util_matrix.h
  test/include/dlaf_test/eigensolver/test_eigensolver_correctness.h
  test/include/dlaf_test/eigensolver/test_gen_eigensolver_correctness.h
  test/unit/eigensolver/test_eigensolver.cpp
Labels: Priority:Medium, Type:Problem

#1021 Enable `copy` to be used with MatrixRef
  include/dlaf/common/index2d.h
  include/dlaf/matrix/copy.h
  test/unit/matrix/CMakeLists.txt
  test/unit/matrix/test_copy.cpp
  test/unit/matrix/test_matrix.cpp
Labels: Type:New Feature

#1041 Fix scal usage in eigensolver tests
  test/include/dlaf_test/eigensolver/test_eigensolver_correctness.h
  test/include/dlaf_test/eigensolver/test_gen_eigensolver_correctness.h
Labels: Priority:Medium, Type:Cleanup, Type:Problem

#1043 Fix compilation flags
  cmake/DLAF_AddTargetWarnings.cmake
Labels: Type:Bug, Priority:Urgent

#1045 Restructure the code such that it can be compiled with nvcc 11.2
  include/dlaf/eigensolver/tridiag_solver/gpu/kernels.h
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/eigensolver/tridiag_solver/kernels.h
  include/dlaf/eigensolver/tridiag_solver/kernels_async.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  src/CMakeLists.txt
  src/eigensolver/tridiag_solver/gpu/kernels.cu
  src/eigensolver/tridiag_solver/kernels.cpp
  src/eigensolver/tridiag_solver/kernels.cu
Labels: Type:Bug, Priority:Urgent

#1048 add --logx ang --logy options to plot scripts
  scripts/postprocess.py
Labels: Type:New Feature, Priority:Low

#1050 Unify docs actions and automate release documentation generation
  .github/workflows/doc-push.yml
  .github/workflows/doc.yml
Labels: Category:Documentation, Type:New Feature, Category:CI, Priority:Medium, Type:Release

#1055 Remove hohgant from system configs
  scripts/systems.py
Labels: Priority:Low

#969 Enable Gemm (local) to be used with MatrixRef
  include/dlaf/blas/tile_extensions.h
  include/dlaf/matrix/matrix_base.h
  include/dlaf/multiplication/general.h
  include/dlaf/multiplication/general/api.h
  include/dlaf/multiplication/general/impl.h
  include/dlaf/util_matrix.h
  test/include/dlaf_test/matrix/util_generic_blas.h
  test/include/dlaf_test/matrix/util_matrix.h
  test/include/dlaf_test/matrix/util_tile_blas.h
  test/unit/matrix/test_copy.cpp
  test/unit/multiplication/test_multiplication_general.cpp
  test/unit/test_blas_tile/test_gemm.h
Labels: Type:New Feature, Priority:Medium

#1054 Revise spack environments
  ci/cuda/gcc11_release_scalapack.yml
  ci/docker/common.yaml
  ci/docker/debug-cpu-stdexec.yaml
  ci/docker/debug-cpu.yaml
  ci/docker/debug-cuda-scalapack.yaml
  ci/docker/debug-cuda.yaml
  ci/docker/release-cpu-serial.yaml
  ci/docker/release-cpu-stdexec.yaml
  ci/docker/release-cpu.yaml
  ci/docker/release-cuda-scalapack.yaml
  ci/docker/release-cuda.yaml
  ci/docker/release-rocm533-stdexec.yaml
  ci/docker/release-rocm533.yaml
Labels: Category:CI, Priority:High, Type:Problem

#1052 Update package after v0.3.1 release
  spack/packages/dla-future/package.py
Labels: Priority:Medium

#1046 Remove rocthrust and rocprim from dependencies
  CMakeLists.txt
  ci/ctest_to_gitlab.sh
  ci/docker/release-rocm533-stdexec.yaml
  ci/docker/release-rocm533.yaml
  ci/rocm/clang14_release.yml
  ci/rocm/clang14_release_stdexec.yml
  cmake/template/DLAFConfig.cmake.in
  include/dlaf/gpu/cub/api.cu.h
  spack/packages/dla-future/package.py
  src/CMakeLists.txt
Labels: Priority:Medium, Type:Cleanup

#1047 Panel: add limited functionality for Matrix with offset
  include/dlaf/matrix/matrix.h
  include/dlaf/matrix/panel.h
  test/unit/matrix/test_panel.cpp
Labels: Type:New Feature, Priority:High

#951 TridiagSolver (local): reduce GEMM step computational cost
  include/dlaf/eigensolver/tridiag_solver/merge.h
Labels: Priority:High, Type:Optimization
