Repository eth-cscs/DLA-Future, pull requests merged in 2023-08, with the labels that each got.

#942 Public algorithm interface renaming using snake_case
  include/dlaf/auxiliary/norm.h
  include/dlaf/eigensolver/band_to_tridiag.h
  include/dlaf/eigensolver/band_to_tridiag/api.h
  include/dlaf/eigensolver/bt_band_to_tridiag.h
  include/dlaf/eigensolver/bt_reduction_to_band.h
  include/dlaf/eigensolver/eigensolver.h
  include/dlaf/eigensolver/eigensolver/api.h
  include/dlaf/eigensolver/eigensolver/impl.h
  include/dlaf/eigensolver/gen_eigensolver.h
  include/dlaf/eigensolver/gen_eigensolver/impl.h
  include/dlaf/eigensolver/gen_to_std.h
  include/dlaf/eigensolver/gen_to_std/api.h
  include/dlaf/eigensolver/gen_to_std/impl.h
  include/dlaf/eigensolver/reduction_to_band.h
  include/dlaf/eigensolver/tridiag_solver.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/factorization/cholesky.h
  include/dlaf/factorization/cholesky/api.h
  include/dlaf/factorization/cholesky/impl.h
  include/dlaf/multiplication/general.h
  include/dlaf/multiplication/hermitian.h
  include/dlaf/multiplication/triangular.h
  include/dlaf/multiplication/triangular/api.h
  include/dlaf/multiplication/triangular/impl.h
  include/dlaf/solver/triangular.h
  include/dlaf/solver/triangular/api.h
  include/dlaf/solver/triangular/impl.h
  miniapp/miniapp_band_to_tridiag.cpp
  miniapp/miniapp_bt_band_to_tridiag.cpp
  miniapp/miniapp_bt_reduction_to_band.cpp
  miniapp/miniapp_cholesky.cpp
  miniapp/miniapp_eigensolver.cpp
  miniapp/miniapp_gen_eigensolver.cpp
  miniapp/miniapp_gen_to_std.cpp
  miniapp/miniapp_reduction_to_band.cpp
  miniapp/miniapp_triangular_solver.cpp
  miniapp/miniapp_tridiag_solver.cpp
  src/c_api/eigensolver/eigensolver.h
  src/c_api/factorization/cholesky.h
  test/unit/auxiliary/mc/test_norm.cpp
  test/unit/c_api/eigensolver/test_eigensolver_c_api.cpp
  test/unit/eigensolver/test_band_to_tridiag.cpp
  test/unit/eigensolver/test_bt_band_to_tridiag.cpp
  test/unit/eigensolver/test_bt_reduction_to_band.cpp
  test/unit/eigensolver/test_eigensolver.cpp
  test/unit/eigensolver/test_gen_eigensolver.cpp
  test/unit/eigensolver/test_gen_to_std.cpp
  test/unit/eigensolver/test_reduction_to_band.cpp
  test/unit/eigensolver/test_tridiag_solver_distributed.cpp
  test/unit/eigensolver/test_tridiag_solver_local.cpp
  test/unit/factorization/test_cholesky.cpp
  test/unit/multiplication/test_multiplication_general.cpp
  test/unit/multiplication/test_multiplication_hermitian.cpp
  test/unit/multiplication/test_multiplication_triangular.cpp
  test/unit/solver/test_triangular.cpp
Labels: Priority:High

#952 minor: fix typos
  include/dlaf/eigensolver/tridiag_solver/merge.h
Labels: Type:Cleanup

#946 Reimplementation of distributed band-to-tridiagonal
  include/dlaf/eigensolver/band_to_tridiag/mc.h
Labels: Priority:High, Type:Optimization

#962 Add placeholder for v0.2.0 documentation
  README.md
Labels: Category:Documentation, Priority:High, Type:Release
