Repository eth-cscs/DLA-Future, pull requests merged in 2023-04, with the labels that each got.

#811 Update spack hash to use pika 0.14.0 in CI
  ci/.gitlab-ci.yml
Labels: RTMWTP

#825 Fix typo in assignment test names
  test/unit/matrix/test_tile.cpp
  test/unit/memory/test_memory_chunk.cpp
  test/unit/memory/test_memory_view.cpp
Labels: RTMWTP, Priority:Low

#822 Assert that band size is at least 2 in reduction to band
  include/dlaf/eigensolver/reduction_to_band.h
Labels: RTMWTP

#827 Fix small typos in `test_matrix`
  test/unit/matrix/test_matrix.cpp
Labels: bug, RTMWTP

#823 Assert that band size is at least 2 in band to tridiagonal backtransformation
  include/dlaf/eigensolver/bt_band_to_tridiag.h
  test/unit/eigensolver/test_bt_band_to_tridiag.cpp
Labels: RTMWTP

#824 Fix bt_reduction_to_band
  include/dlaf/eigensolver/bt_reduction_to_band/impl.h
  test/unit/eigensolver/test_bt_reduction_to_band.cpp
Labels: bug, RTMWTP

#820 Add eigensolver for pre-allocated eigenvalues and eigenvector matrices
  include/dlaf/eigensolver/eigensolver.h
  include/dlaf/eigensolver/eigensolver/api.h
  include/dlaf/eigensolver/eigensolver/impl.h
  test/unit/eigensolver/test_eigensolver.cpp
Labels: RTMWTP

#828 Add orthogonality test to tridiagonal eigensolver tests
  test/include/dlaf_test/eigensolver/test_eigensolver_correctness.h
  test/unit/eigensolver/test_eigensolver.cpp
  test/unit/eigensolver/test_tridiag_solver_distributed.cpp
  test/unit/eigensolver/test_tridiag_solver_local.cpp
Labels: Priority:High

#832 Improve plot scripts
  scripts/postprocess.py
Labels: enhancement

#831 Remove the need of the distributed row permutation in the tridiagonal solver.
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/eigensolver/tridiag_solver/kernels.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  src/eigensolver/tridiag_solver/kernels.cpp
  src/eigensolver/tridiag_solver/kernels.cu
Labels: Priority:High

#807 Split application of HH reflector block in bt_band_to_tridiag
  include/dlaf/eigensolver/bt_band_to_tridiag/impl.h
  include/dlaf/tune.h
  src/init.cpp
  test/unit/eigensolver/test_bt_band_to_tridiag.cpp
Labels: Priority:High, Optimization

#835 Permute Distributed: migrate from AllToAll to Send/Recv
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/permutations/general.h
  include/dlaf/permutations/general/api.h
  include/dlaf/permutations/general/impl.h
  test/src/gtest_mpi_listener.cpp
  test/unit/permutations/test_permutations_distributed.cpp
  test/unit/permutations/test_permutations_local.cpp
Labels: Priority:High
