Repository eth-cscs/DLA-Future, pull requests merged in 2023-01, with the labels that each got.

#757 Fix band2tridiagonal
  include/dlaf/eigensolver/band_to_tridiag/mc.h
  test/unit/eigensolver/test_band_to_tridiag.cpp
Labels: bug, Priority:High

#752 Introduce sub-band in the eigensolver
  include/dlaf/eigensolver/eigensolver/impl.h
  include/dlaf/eigensolver/get_band_size.h
  include/dlaf/tune.h
  miniapp/miniapp_eigensolver.cpp
  miniapp/miniapp_gen_eigensolver.cpp
  scripts/gen_dlaf_strong.py
  scripts/gen_dlaf_weak.py
  scripts/miniapps.py
  scripts/postprocess.py
  src/CMakeLists.txt
  src/init.cpp
  src/tune.cpp
  test/unit/eigensolver/test_eigensolver.cpp
  test/unit/eigensolver/test_gen_eigensolver.cpp
Labels: Priority:Medium

#759 Fix minor typo in `test_permutations_distributed`
  test/unit/permutations/test_permutations_distributed.cpp
Labels: Priority:Low

#774 hermitian matrix multiplication (left lower)
  include/dlaf/multiplication/hermitian.h
  include/dlaf/multiplication/hermitian/api.h
  include/dlaf/multiplication/hermitian/impl.h
  src/CMakeLists.txt
  src/multiplication/hermitian/gpu.cpp
  src/multiplication/hermitian/mc.cpp
  test/include/dlaf_test/matrix/util_generic_blas.h
  test/unit/multiplication/CMakeLists.txt
  test/unit/multiplication/test_multiplication_hermitian.cpp
  test/unit/test_blas_tile/test_hemm.h
Labels: Priority:High

#776 add check to eigensolver miniapp
  include/dlaf/auxiliary/norm.h
  include/dlaf/auxiliary/norm/api.h
  include/dlaf/auxiliary/norm/mc.h
  include/dlaf/blas/scal.h
  miniapp/include/dlaf/miniapp/scale_eigenvectors.h
  miniapp/miniapp_cholesky.cpp
  miniapp/miniapp_eigensolver.cpp
  miniapp/miniapp_gen_eigensolver.cpp
  src/CMakeLists.txt
  src/auxiliary/norm/mc.cpp
  src/blas/scal.cpp
  test/unit/auxiliary/mc/test_norm.cpp
Labels: Priority:High

#783 Fix plot title generation in `postprocess.py`
  scripts/postprocess.py
Labels: bug
