Repository eth-cscs/DLA-Future, pull requests merged in 2023-10, with the labels that each got.

#999 Fix Cholesky priorities
  include/dlaf/factorization/cholesky/impl.h
Labels: Priority:High, Type:Performance issue

#990 Print tune parameters with `--dlaf:print-config`
  include/dlaf/init.h
  include/dlaf/tune.h
  src/init.cpp
  src/tune.cpp
Labels: Type:New Feature, Priority:Low

#1000 Enable tests in CI for stdexec in debug mode
  ci/.gitlab-ci.yml
Labels: Category:CI

#983 Fix linking issues with HDF5 when using DLAF as dependency and enable HDF5 in CI
  ci/ctest_to_gitlab.sh
  ci/docker/codecov.Dockerfile
  ci/docker/debug-cuda-scalapack.yaml
  cmake/template/DLAFConfig.cmake.in
  test/unit/matrix/test_matrix_hdf5.cpp
Labels: Category:CI, Priority:Low, Type:Problem

#1001 Fix triangular solver/multiplication documentation
  include/dlaf/multiplication/triangular.h
  include/dlaf/solver/triangular.h
Labels: Category:Documentation, Priority:Urgent, Type:Problem

#1002 Fix coverage tests
  ci/docker/debug-cpu.yaml
  ci/docker/debug-cuda.yaml
Labels: Type:Bug, Category:CI, Priority:High

#988 extend build stage from CI/CD container build
  ci/.gitlab-ci.yml
  ci/common-ci.yml
  ci/cpu/clang12_release.yml
  ci/cpu/clang13_release_cxx20.yml
  ci/cpu/gcc11_codecov.yml
  ci/cpu/gcc11_debug_stdexec.yml
  ci/cpu/gcc11_release.yml
  ci/cpu/gcc11_release_stdexec.yml
  ci/cpu/gcc12_release_cxx20.yml
  ci/cuda/gcc11_codecov.yml
  ci/cuda/gcc11_debug_scalapack.yml
  ci/cuda/gcc11_release.yml
  ci/cuda/gcc11_release_scalapack.yml
  ci/docker/build.Dockerfile
  ci/docker/codecov.Dockerfile
  ci/docker/deploy.Dockerfile
  ci/rocm/clang14_release.yml
Labels: Category:CI, Priority:Low, Type:Cleanup

#1003 Disabling stdexec debug test as occasional failure
  ci/cpu/gcc11_debug_stdexec.yml
Labels: Priority:Urgent, Category:CI

#1009 Add error message for invalid grid context in C API
  .clang-format
  src/c_api/eigensolver/eigensolver.h
  src/c_api/eigensolver/gen_eigensolver.h
  src/c_api/factorization/cholesky.h
  src/c_api/utils.cpp
  src/c_api/utils.h
Labels: Priority:Low, Type:Problem

#976 Refactor distribution and extend tests for sub-distributions
  include/dlaf/matrix/distribution.h
  include/dlaf/matrix/distribution_extensions.h
  include/dlaf/matrix/layout_info.h
  include/dlaf/matrix/util_distribution.h
  src/matrix/distribution.cpp
  test/unit/matrix/CMakeLists.txt
  test/unit/matrix/test_distribution.cpp
  test/unit/matrix/test_distribution_extensions.cpp
  test/unit/matrix/test_util_distribution.cpp
Labels: Type:New Feature, Priority:High, Type:Refactoring, Type:Cleanup

#1010 Enable complex in gen_* scripts
  scripts/gen_dlaf_strong-gpu.py
  scripts/gen_dlaf_strong-mc.py
  scripts/gen_dlaf_weak-gpu.py
  scripts/gen_dlaf_weak-mc.py
  scripts/miniapps.py
Labels: Type:New Feature, Priority:High

#1015 enable complex in miniapp tridiagonal eigensolver
  miniapp/miniapp_tridiag_solver.cpp
Labels: Type:New Feature, Priority:Medium

#1019 Cleanup unused GPU kernels
  include/dlaf/lapack/tile.h
  src/CMakeLists.txt
  src/cusolver/stedc.cu
Labels: Priority:Medium, Type:Cleanup

#1014 Added srun_args option to miniapps.py
  scripts/miniapps.py
  scripts/systems.py
Labels: Type:New Feature, Priority:Medium, Type:Cleanup
