Repository eth-cscs/DLA-Future, pull requests merged in 2023-05, with the labels that each got.

#852 bump gtest version to remove bogus cmake warning
  external/CMakeLists.txt
Labels: Type:Bug

#863 Print binary sizes in CI
  ci/docker/codecov.Dockerfile
  ci/docker/deploy.Dockerfile
Labels: Category:CI, Priority:Low

#843 tridiagonal eigensolver: uniformize usage of end index
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/eigensolver/tridiag_solver/index_manipulation.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/eigensolver/tridiag_solver/rot.h
  include/dlaf/eigensolver/tridiag_solver/tile_collector.h
  include/dlaf/matrix/distribution.h
  include/dlaf/multiplication/general.h
  include/dlaf/multiplication/general/impl.h
  include/dlaf/permutations/general.h
  include/dlaf/permutations/general/impl.h
  test/include/dlaf_test/matrix/util_generic_blas.h
  test/unit/eigensolver/test_tridiag_solver_local.cpp
  test/unit/eigensolver/test_tridiag_solver_merge.cpp
  test/unit/eigensolver/test_tridiag_solver_rot.cpp
  test/unit/multiplication/test_multiplication_general.cpp
  test/unit/permutations/test_permutations_distributed.cpp
  test/unit/permutations/test_permutations_local.cpp
Labels: Priority:Medium, Type:Cleanup

#834 Keep `-Werror` flags in CI
  ci/docker/codecov.Dockerfile
  ci/docker/deploy.Dockerfile
  include/dlaf/lapack/tile.h
  include/dlaf/multiplication/general.h
  include/dlaf/util_blas.h
  src/cusolver/assert_info.cu
  src/matrix/layout_info.cpp
  test/include/dlaf_test/matrix/util_generic_blas.h
  test/src/gtest_mpi_listener.cpp
  test/unit/communication/test_communicator_grid.cpp
  test/unit/communication/test_transform_mpi.cpp
Labels: Priority:High

#858 Remove not needed column permutations
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/eigensolver/tridiag_solver/index_manipulation.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
Labels: Priority:High, Type:Optimization, Type:Cleanup

#879 bug fix: warnings as errors for cuda/rocm were not enabled
  spack/packages/dla-future/package.py
Labels: Category:CI

#874 Only ignore `build*` in root of repository
  .gitignore
Labels: Priority:High, Type:Cleanup

#853 Add GCC 12 CI configuration
  ci/.gitlab-ci.yml
  include/dlaf/eigensolver/band_to_tridiag/mc.h
  test/unit/matrix/test_matrix_output.cpp
Labels: Category:CI, Priority:Medium

#881 Minor updates to `Pipeline`, `TilePipeline`, and `Tile`
  include/dlaf/common/pipeline.h
  include/dlaf/matrix/internal/tile_pipeline.h
  include/dlaf/matrix/retiled_matrix.h
  include/dlaf/matrix/tile.h
  test/unit/common/test_pipeline.cpp
  test/unit/matrix/test_tile.cpp
Labels: Type:Cleanup

#884 Automatically upload master doxygen documentation to github pages.
  .github/workflows/doc-push.yml
  .github/workflows/doc.yml
  README.md
Labels: Category:Documentation, Priority:Urgent, Category:CI

#885 Allow empty commit when pushing doc
  .github/workflows/doc-push.yml
Labels: Type:Bug, Category:Documentation, Category:CI, Priority:High

#887 V and W should not be computed if no columns of the matrix has to be updated.
  include/dlaf/eigensolver/bt_band_to_tridiag/impl.h
Labels: Type:Performance issue, Priority:Low, Type:Cleanup
