Repository eth-cscs/DLA-Future, pull requests merged in 2023-06, with the labels that each got.

#896 Fix tridiagonal eigensolver when the rank 1 problem size is 2
  include/dlaf/eigensolver/tridiag_solver/merge.h
  src/eigensolver/tridiag_solver/kernels.cpp
  src/eigensolver/tridiag_solver/kernels.cu
  test/unit/eigensolver/test_tridiag_solver_distributed.cpp
  test/unit/eigensolver/test_tridiag_solver_local.cpp
Labels: Type:Bug, Priority:High

#899 update spack package maintainers
  spack/packages/dla-future/package.py
Labels: Priority:Urgent, Type:Release

#900 Add placeholder for v0.1.0 documentation
  README.md
Labels: Category:Documentation, Priority:High, Type:Release

#864 Use busy waiting barrier in reduction to band
  ci/.gitlab-ci.yml
  include/dlaf/eigensolver/internal/get_red2band_barrier_busy_wait.h
  include/dlaf/eigensolver/internal/get_tridiag_rank1_barrier_busy_wait.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/tune.h
  spack/packages/dla-future/package.py
  src/init.cpp
Labels: Priority:High

#911 Use `unique_ptr` instead of `shared_ptr` for `barrier` in tridiag_solver
  include/dlaf/eigensolver/tridiag_solver/merge.h
Labels: Priority:Medium, Type:Refactoring
