Repository eth-cscs/DLA-Future, pull requests merged in 2023-02, with the labels that each got.

#795 Add "--local" option to miniapps
  include/dlaf/eigensolver/bt_reduction_to_band.h
  include/dlaf/eigensolver/bt_reduction_to_band/api.h
  include/dlaf/eigensolver/bt_reduction_to_band/impl.h
  include/dlaf/eigensolver/eigensolver/impl.h
  miniapp/include/dlaf/miniapp/options.h
  miniapp/miniapp_band_to_tridiag.cpp
  miniapp/miniapp_bt_band_to_tridiag.cpp
  miniapp/miniapp_bt_reduction_to_band.cpp
  miniapp/miniapp_cholesky.cpp
  miniapp/miniapp_eigensolver.cpp
  miniapp/miniapp_gen_eigensolver.cpp
  miniapp/miniapp_gen_to_std.cpp
  miniapp/miniapp_reduction_to_band.cpp
  miniapp/miniapp_triangular_solver.cpp
  miniapp/miniapp_tridiag_solver.cpp
  test/unit/eigensolver/test_bt_reduction_to_band.cpp
Labels: Priority:Low

#794 Fix warning about unused typedef
  include/dlaf/eigensolver/tridiag_solver/kernels.h
Labels: Priority:High

#796 Add tile sum kernel
  include/dlaf/blas/tile_extensions.h
  include/dlaf/lapack/gpu/add.h
  include/dlaf/util_cuda.h
  src/CMakeLists.txt
  src/lapack/gpu/add.cu
Labels: Priority:High, Optimization

#801 fix error showing up in the CI.
  test/unit/eigensolver/test_band_to_tridiag.cpp
Labels: bug, Priority:High
