Repository eth-cscs/DLA-Future, pull requests merged in 2023-09, with the labels that each got.

#943 TridiagSolver (local): sort eigenvalues by column type for rank1 solver
  include/dlaf/eigensolver/tridiag_solver/coltype.h
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
Labels: Priority:Medium

#971 Doc fixes for TridiagSolver (local) and removal of unused GPU kernels
  include/dlaf/eigensolver/tridiag_solver/index_manipulation.h
  include/dlaf/eigensolver/tridiag_solver/kernels.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  src/eigensolver/tridiag_solver/kernels.cpp
  src/eigensolver/tridiag_solver/kernels.cu
Labels: Priority:Low, Type:Cleanup

#973 Add HDF5 input and output files to eigensolver miniapp
  miniapp/miniapp_eigensolver.cpp
  miniapp/miniapp_tridiag_solver.cpp
Labels: Type:New Feature, Priority:Low

#979 Remove `strategy: depend` clause as already in .run_common CI step
  ci/.gitlab-ci.yml
Labels: Category:CI

#985 Remove unecessary `GIT_SUBMODULE_STRATEGY` from CI
  ci/.gitlab-ci.yml
Labels: Category:CI

#986 Add placeholder for v0.2.1 doc
  README.md
Labels: Category:Documentation, Priority:High, Type:Release

#987 Update package after v0.2.1 release
  spack/packages/dla-future/package.py
Labels: Priority:High, Type:Release

#945 Remove use of `pika::for_loop` from permutations
  CMakeLists.txt
  ci/.gitlab-ci.yml
  ci/docker/release-cpu-stdexec.yaml
  cmake/template/DLAFConfig.cmake.in
  include/dlaf/permutations/general/impl.h
  spack/packages/dla-future/package.py
  src/CMakeLists.txt
Labels: Priority:Medium

#992 C and ScaLAPACK-like API for generalised eigensolver
  include/dlaf_c/eigensolver/eigensolver.h
  include/dlaf_c/eigensolver/gen_eigensolver.h
  src/CMakeLists.txt
  src/c_api/eigensolver/gen_eigensolver.cpp
  src/c_api/eigensolver/gen_eigensolver.h
  test/include/dlaf_test/eigensolver/test_gen_eigensolver_correctness.h
  test/include/dlaf_test/matrix/util_matrix_local.h
  test/unit/c_api/eigensolver/CMakeLists.txt
  test/unit/c_api/eigensolver/test_gen_eigensolver_c_api.cpp
  test/unit/c_api/eigensolver/test_gen_eigensolver_c_api_wrapper.c
  test/unit/c_api/eigensolver/test_gen_eigensolver_c_api_wrapper.h
  test/unit/eigensolver/test_gen_eigensolver.cpp
Labels: Type:New Feature, Priority:High

#975 Add HDF5 input and output to reduction_to_band miniapp
  miniapp/miniapp_reduction_to_band.cpp
Labels: Type:New Feature, Priority:Low
