Repository eth-cscs/DLA-Future, pull requests merged in 2023-12, with the labels that each got.

#1022 Enable Gemm (distributed) to be used with MatrixRef
  include/dlaf/multiplication/general.h
  include/dlaf/multiplication/general/api.h
  include/dlaf/multiplication/general/impl.h
  include/dlaf/util_matrix.h
  test/unit/multiplication/test_multiplication_general.cpp
Labels: Type:New Feature, Priority:High

#1063 Fix compilation with GCC 13
  include/dlaf/blas/scal.h
  src/blas/scal.cpp
Labels: Category:CI

#1066 Use f-strings in the spack package
  spack/packages/dla-future/package.py
Labels: Type:Cleanup

#967 TridiagSolver (dist): STEP1 rank-independent sort of eigenvalues by column type for rank1 solver
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/permutations/general/impl.h
  test/unit/eigensolver/test_tridiag_solver_merge.cpp
Labels: Priority:High, Type:Optimization

#996 TridiagSolver (dist): STEP2 Make rank1 work just on local non-deflated eigenvectors
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/eigensolver/tridiag_solver/index_manipulation.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
Labels: Priority:High

#1004 Use `drop_operation_state` to avoid stack overflows
  CMakeLists.txt
  ci/cpu/gcc11_debug_stdexec.yml
  ci/docker/debug-cpu-stdexec.yaml
  include/dlaf/eigensolver/band_to_tridiag/mc.h
  include/dlaf/sender/transform.h
  include/dlaf/sender/transform_mpi.h
  spack/packages/dla-future/package.py
Labels: Type:Bug, Priority:High

#998 TridiagSolver (dist): STEP3 reduce GEMM step computational cost
  include/dlaf/eigensolver/tridiag_solver/merge.h
Labels: Priority:High
