Repository eth-cscs/DLA-Future, pull requests merged in 2023-07, with the labels that each got.

#926 Update CUDA Docker container image
  ci/.gitlab-ci.yml
Labels: Priority:Urgent, Category:CI

#924 Ignore doxygen html folder
  .gitignore
Labels: Category:Documentation, Priority:Low, Type:Cleanup

#927 fix version specifier for a ci spec
  ci/docker/release-cpu-stdexec.yaml
Labels: Type:Bug, Priority:Urgent, Category:CI

#908 Replace use of `shared_future` for taus by `Matrix`
  include/dlaf/common/unwrap.h
  include/dlaf/eigensolver/band_to_tridiag/mc.h
  include/dlaf/eigensolver/bt_reduction_to_band.h
  include/dlaf/eigensolver/bt_reduction_to_band/api.h
  include/dlaf/eigensolver/bt_reduction_to_band/impl.h
  include/dlaf/eigensolver/eigensolver/impl.h
  include/dlaf/eigensolver/reduction_to_band.h
  include/dlaf/eigensolver/reduction_to_band/api.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
  include/dlaf/factorization/qr.h
  include/dlaf/factorization/qr/api.h
  include/dlaf/factorization/qr/t_factor_impl.h
  include/dlaf/matrix/matrix_base.h
  include/dlaf/sender/keep_future.h
  include/dlaf/sender/traits.h
  miniapp/miniapp_bt_reduction_to_band.cpp
  miniapp/miniapp_reduction_to_band.cpp
  test/unit/communication/test_comm_sender.cpp
  test/unit/eigensolver/test_bt_reduction_to_band.cpp
  test/unit/eigensolver/test_reduction_to_band.cpp
  test/unit/factorization/test_compute_t_factor.cpp
Labels: Priority:Medium, Type:Refactoring

#901 Allow incomplete first tile/block in `Distribution`
  include/dlaf/matrix/distribution.h
  include/dlaf/matrix/util_distribution.h
  src/matrix/distribution.cpp
  test/unit/matrix/test_distribution.cpp
Labels: Type:New Feature, Priority:High

#904 TridiagSolver (distributed): "bulkerify" rank1 problem solution
  include/dlaf/eigensolver/tridiag_solver/merge.h
Labels: Priority:High, Type:Optimization, Type:Cleanup

#913 minor: introduce parseFromString for bools
  src/init.cpp
Labels: Type:New Feature, Priority:Medium

#906 TridiagSolver: remove unused kernels
  include/dlaf/eigensolver/tridiag_solver/kernels.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  src/eigensolver/tridiag_solver/kernels.cpp
  src/eigensolver/tridiag_solver/kernels.cu
Labels: Priority:Low, Type:Cleanup

#880 Introduce HDF5
  CMakeLists.txt
  cmake/template/DLAFConfig.cmake.in
  include/dlaf/eigensolver/eigensolver/impl.h
  include/dlaf/matrix/hdf5.h
  include/dlaf/tune.h
  miniapp/miniapp_tridiag_solver.cpp
  spack/packages/dla-future/package.py
  src/CMakeLists.txt
  src/init.cpp
  src/matrix/hdf5.cpp
  test/unit/matrix/CMakeLists.txt
  test/unit/matrix/test_matrix_hdf5.cpp
Labels: Type:New Feature, Priority:High

#932 Fix actions
  .github/workflows/check_format.yml
  .github/workflows/doc-push.yml
  .github/workflows/doc.yml
Labels: Type:Bug, Priority:Urgent, Category:CI

#912 TridiagSolver: number of bulk workers for rank1 solver
  include/dlaf/eigensolver/internal/get_tridiag_rank1_nworkers.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/tune.h
Labels: Priority:Low, Type:Optimization

#937 minor: reduce code duplication for TridiagSolver workspaces
  include/dlaf/eigensolver/tridiag_solver/merge.h
Labels: Priority:Low, Type:Cleanup

#936 TridiagSolver (local): embed row permutation in rank1 solver
  include/dlaf/eigensolver/tridiag_solver/kernels.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  src/eigensolver/tridiag_solver/kernels.cpp
  src/eigensolver/tridiag_solver/kernels.cu
Labels: Priority:Medium

#935 Refactor `RetiledMatrix` into `Matrix`
  include/dlaf/auxiliary/norm.h
  include/dlaf/eigensolver/band_to_tridiag.h
  include/dlaf/eigensolver/bt_band_to_tridiag.h
  include/dlaf/eigensolver/bt_band_to_tridiag/impl.h
  include/dlaf/eigensolver/bt_reduction_to_band.h
  include/dlaf/eigensolver/eigensolver.h
  include/dlaf/eigensolver/gen_eigensolver.h
  include/dlaf/eigensolver/gen_to_std.h
  include/dlaf/eigensolver/reduction_to_band.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
  include/dlaf/eigensolver/tridiag_solver.h
  include/dlaf/factorization/cholesky.h
  include/dlaf/matrix/matrix.h
  include/dlaf/matrix/matrix.tpp
  include/dlaf/matrix/matrix_const.tpp
  include/dlaf/matrix/retiled_matrix.h
  include/dlaf/multiplication/general.h
  include/dlaf/multiplication/hermitian.h
  include/dlaf/multiplication/triangular.h
  include/dlaf/permutations/general.h
  include/dlaf/solver/triangular.h
  include/dlaf/util_matrix.h
  src/CMakeLists.txt
  src/matrix/retiled_matrix.cpp
  test/unit/matrix/test_retiled_matrix.cpp
Labels: Priority:High

#941 Avoid unnecessary allocation of `shared_ptr`s in `MemoryView`
  include/dlaf/memory/memory_chunk.h
  include/dlaf/memory/memory_view.h
Labels: Priority:Low

#938 Reimplementation of local band-to-tridiagonal
  include/dlaf/eigensolver/band_to_tridiag.h
  include/dlaf/eigensolver/band_to_tridiag/mc.h
  include/dlaf/eigensolver/eigensolver/impl.h
  miniapp/miniapp_band_to_tridiag.cpp
  test/unit/eigensolver/test_band_to_tridiag.cpp
Labels: Priority:High

#909 Support different tile and block size in `Matrix`
  include/dlaf/matrix/distribution.h
  include/dlaf/matrix/matrix.tpp
  include/dlaf/matrix/matrix_base.h
  include/dlaf/matrix/matrix_const.tpp
  test/include/dlaf_test/matrix/util_matrix_local.h
  test/unit/eigensolver/test_reduction_to_band.cpp
  test/unit/matrix/test_matrix.cpp
  test/unit/matrix/test_matrix_local.cpp
  test/unit/matrix/test_matrix_mirror.cpp
Labels: Priority:Low

#934 Add `MatrixRef` to take a sub-matrix from an existing `Matrix`
  include/dlaf/matrix/distribution.h
  include/dlaf/matrix/matrix_ref.h
  src/CMakeLists.txt
  src/matrix/distribution.cpp
  src/matrix/matrix_ref.cpp
  test/unit/matrix/CMakeLists.txt
  test/unit/matrix/test_distribution.cpp
  test/unit/matrix/test_matrix_ref.cpp
Labels: Priority:High

#886 ScaLAPACK-like interface for Cholesky decomposition and eigensolver
  .github/workflows/check_license_header.yaml
  .gitignore
  CMakeLists.txt
  ci/.gitlab-ci.yml
  ci/docker/debug-cuda-scalapack.yaml
  ci/docker/release-cuda-scalapack.yaml
  cmake/DLAF_AddTargetWarnings.cmake
  cmake/DLAF_AddTest.cmake
  cmake/FindSCALAPACK.cmake
  cmake/template/DLAFConfig.cmake.in
  doc/Doxyfile.in
  include/dlaf_c/desc.h
  include/dlaf_c/eigensolver/eigensolver.h
  include/dlaf_c/factorization/cholesky.h
  include/dlaf_c/grid.h
  include/dlaf_c/init.h
  include/dlaf_c/utils.h
  spack/packages/dla-future/package.py
  src/CMakeLists.txt
  src/c_api/blacs.h
  src/c_api/eigensolver/eigensolver.cpp
  src/c_api/eigensolver/eigensolver.h
  src/c_api/factorization/cholesky.cpp
  src/c_api/factorization/cholesky.h
  src/c_api/grid.cpp
  src/c_api/grid.h
  src/c_api/init.cpp
  src/c_api/utils.cpp
  src/c_api/utils.h
  test/include/dlaf_c_test/blacs.h
  test/include/dlaf_c_test/c_api_helpers.h
  test/include/dlaf_c_test/config.h.in
  test/include/dlaf_test/comm_grids/grids_6_ranks.h
  test/src/gtest_mpi_main.cpp
  test/unit/CMakeLists.txt
  test/unit/c_api/eigensolver/CMakeLists.txt
  test/unit/c_api/eigensolver/test_eigensolver_c_api.cpp
  test/unit/c_api/eigensolver/test_eigensolver_c_api_wrapper.c
  test/unit/c_api/eigensolver/test_eigensolver_c_api_wrapper.h
  test/unit/c_api/factorization/CMakeLists.txt
  test/unit/c_api/factorization/test_cholesky_c_api.cpp
  test/unit/c_api/factorization/test_cholesky_c_api_wrapper.c
  test/unit/c_api/factorization/test_cholesky_c_api_wrapper.h
  test/unit/c_api/grid/CMakeLists.txt
  test/unit/c_api/grid/test_grid_c_api.cpp
  test/unit/c_api/grid/test_grid_c_api_wrapper.c
  test/unit/c_api/grid/test_grid_c_api_wrapper.h
Labels: Type:New Feature, Priority:High
