Repository eth-cscs/DLA-Future, pull requests merged in 2024-12, with the labels that each got.

#1192 CI move to ALPS (daint-mc -> eiger)
  ci/common-ci.yml
  ci/cpu/asan_ubsan_lsan.yml
  ci/cpu/clang15_release.yml
  ci/cpu/clang15_release_cxx20.yml
  ci/cpu/clang15_release_stdexec.yml
  ci/cpu/clang16_release.yml
  ci/cpu/clang18_release.yml
  ci/cpu/gcc11_debug_stdexec.yml
  ci/cpu/gcc11_release_stdexec.yml
  ci/cpu/gcc12_release_cxx20.yml
  ci/cpu/gcc13_codecov.yml
  ci/cpu/gcc13_release.yml
  ci/ctest_to_gitlab.sh
Labels: Category:CI, Priority:Medium

#1227 scripts: let the user know if submitting with sbatch failed
  scripts/miniapps.py
Labels: Priority:Low

#1233 Fix timeout issue splitting RANK6 C-API tests
  ci/ctest_to_gitlab.sh
  cmake/DLAF_AddTest.cmake
  test/unit/c_api/eigensolver/CMakeLists.txt
  test/unit/c_api/factorization/CMakeLists.txt
  test/unit/c_api/grid/CMakeLists.txt
Labels: Category:CI, Priority:Medium

#1232 ReductionToBand: Dynamic number of workers for Panel computation (bulk)
  include/dlaf/eigensolver/internal/get_red2band_panel_nworkers.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
Labels: Type:Optimization

#1247 Move CPU CI back to daint-mc
  ci/cpu/asan_ubsan_lsan.yml
  ci/cpu/clang15_release.yml
  ci/cpu/clang15_release_cxx20.yml
  ci/cpu/clang15_release_stdexec.yml
  ci/cpu/clang16_release.yml
  ci/cpu/clang18_release.yml
  ci/cpu/gcc11_debug_stdexec.yml
  ci/cpu/gcc11_release_stdexec.yml
  ci/cpu/gcc12_release_cxx20.yml
  ci/cpu/gcc13_codecov.yml
  ci/cpu/gcc13_release.yml
Labels: Category:CI, Priority:High
