Repository eth-cscs/DLA-Future, pull requests merged in 2024-01, with the labels that each got.

#1071 Revert "boost priority threads for mpi" (Partially revert #1036)
  include/dlaf/sender/transform_mpi.h
Labels: Type:Bug, Priority:High

#1072 Fix wrong bounds of and concurrent access to counter on pipeline test
  test/unit/common/test_pipeline.cpp
Labels: Type:Bug

#1073 Start migrating to Intel oneMKL
  CMakeLists.txt
  README.md
  cmake/template/DLAFConfig.cmake.in
  spack/packages/dla-future/package.py
  src/CMakeLists.txt
Labels: Priority:Low

#1077 Use pika 0.21 and oneapi MKL in CI
  ci/common-ci.yml
  ci/docker/build.Dockerfile
  ci/docker/common.yaml
  ci/docker/deploy.Dockerfile
  ci/docker/release-cpu-serial.yaml
  spack/packages/dla-future/package.py
Labels: Category:CI, Priority:High

#1078 Add placeholder for v0.4.0 doc and update Readme
  README.md
Labels: Category:Documentation, Priority:Medium, Type:Release

#1080 Update package after v0.4.0 release
  spack/packages/dla-future/package.py
Labels: Priority:High, Type:Release

#1081 Limit fastcov jobs to avoid out of memory
  ci/mpi-ctest
Labels: Category:CI, Priority:High, Type:Problem

#1084 Bump spack in CI
  ci/common-ci.yml
  spack/packages/dla-future/package.py
Labels: Category:CI, Priority:Low, Type:Cleanup
