Repository eth-cscs/DLA-Future, pull requests merged in 2024-07, with the labels that each got.

#1173 Update README.md
  README.md
Labels: Category:Documentation, Priority:High

#1175 Update clang-format to latest v18 release.
  .github/workflows/check_format.yml
Labels: Category:CI, Priority:Low

#1164 Instrument distributed generalized eigensolver and Cholesky decomposition with HDF5
  include/dlaf/eigensolver/gen_eigensolver/impl.h
  include/dlaf/eigensolver/gen_to_std/impl.h
  include/dlaf/factorization/cholesky/impl.h
  include/dlaf/tune.h
  miniapp/miniapp_gen_eigensolver.cpp
  src/init.cpp
Labels: Priority:Low
