Repository eth-cscs/DLA-Future, pull requests merged in 2024-05, with the labels that each got.

#1124 Fix CI workaround for custom build directory
  ci/docker/codecov.Dockerfile
  ci/docker/deploy.Dockerfile
Labels: Category:CI, Priority:Low, Type:Cleanup

#1016 Instrument distributed eigensolver with HDF5
  CMakeLists.txt
  ci/common-ci.yml
  include/dlaf/eigensolver/band_to_tridiag/mc.h
  include/dlaf/eigensolver/eigensolver/impl.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/matrix/hdf5.h
  include/dlaf/tune.h
  src/CMakeLists.txt
  src/init.cpp
Labels: Priority:Low

#1139 Improve readme readability moving some documentation details
  DOCUMENTATION.md
  README.md
  RELEASE_PROCEDURE.md
Labels: Category:Documentation, Priority:High

#1138 Move build section to a subpage of README to improve readability
  BUILD.md
  README.md
Labels: Category:Documentation, Priority:High

#1144 Fix performance of local version of bt_band_to_tridiagonal
  include/dlaf/eigensolver/bt_band_to_tridiag/impl.h
Labels: Priority:High, Type:Performance issue

#1146 github actions use ubuntu 2024.04
  .github/workflows/check_format.yml
  .github/workflows/check_license_header.yaml
  .github/workflows/doc.yml
Labels: Category:CI, Priority:Low

#1148 Remove `multiplication::generalSubMatrix`
  include/dlaf/multiplication/general.h
  include/dlaf/multiplication/general/api.h
  include/dlaf/multiplication/general/impl.h
  test/unit/multiplication/test_multiplication_general.cpp
Labels: Priority:Medium, Type:Cleanup

#1150 remove outdated script
  scripts/build.sh
Labels: Priority:High, Type:Cleanup, Type:Release

#1152 Move release script from hub to gh
  RELEASE_PROCEDURE.md
  scripts/roll_release.sh
Labels: Priority:High, Type:Release

#1155 remove outdated INSTALL.md,
  INSTALL.md
Labels: Category:Documentation, Priority:High

#1153 Cleanup matrix setup in miniapp_triangular_solver to enable complex types
  include/dlaf/util_matrix.h
  miniapp/miniapp_triangular_solver.cpp
  test/unit/matrix/test_util_matrix.cpp
Labels: Priority:High, Type:Cleanup, Type:Problem

#1149 Remove most special handling of MKL in CMake configuration
  BUILD.md
  CMakeLists.txt
  ci/common-ci.yml
  ci/docker/build.Dockerfile
  cmake/FindLAPACK.cmake
  cmake/FindMKL.cmake
  cmake/FindSCALAPACK.cmake
  cmake/template/DLAFConfig.cmake.in
  cmake/tests/mkl_set_num_threads.cpp
  spack/packages/dla-future/package.py
  src/CMakeLists.txt
Labels: Type:Bug, Priority:Urgent

#1137 Preparation for v0.5.0 release
  CHANGELOG.md
  CITATION.cff
  CMakeLists.txt
  DOCUMENTATION.md
  README.md
Labels: Type:Release
