Repository eth-cscs/DLA-Future, pull requests merged in 2024-06, with the labels that each got.

#1156 Update spack package post v0.5.0
  ci/docker/release-rocm533.yaml
  spack/packages/dla-future/package.py
Labels: Priority:High, Type:Release

#1162 fix grep and sed usage
  scripts/roll_release.sh
Labels: Priority:High, Type:Release

#1163 Update clang-format and black version
  .clang-format
  .git-blame-ignore-revs
  .github/format.sh
  .github/workflows/check_format.yml
  include/dlaf/common/callable_object.h
  include/dlaf/common/pipeline.h
  include/dlaf/common/source_location.h
  include/dlaf/common/unwrap.h
  include/dlaf/communication/kernels/internal/all_reduce.h
  include/dlaf/matrix/tile.h
  include/dlaf/sender/transform_mpi.h
  include/dlaf/util_math.h
  src/init.cpp
  test/unit/c_api/eigensolver/test_eigensolver_c_api.cpp
  test/unit/communication/test_comm_matrix.cpp
  test/unit/eigensolver/test_eigensolver.cpp
  test/unit/matrix/test_copy.cpp
  test/unit/matrix/test_util_matrix.cpp
Labels: Category:CI, Priority:High, Type:Cleanup

#1168 Rename pxhegvx to pxhegvd
  CHANGELOG.md
  include/dlaf_c/eigensolver/gen_eigensolver.h
  src/c_api/eigensolver/gen_eigensolver.cpp
  src/c_api/eigensolver/gen_eigensolver.h
  test/unit/c_api/eigensolver/test_gen_eigensolver_c_api.cpp
  test/unit/c_api/eigensolver/test_gen_eigensolver_c_api_wrapper.c
  test/unit/c_api/eigensolver/test_gen_eigensolver_c_api_wrapper.h
Labels: Priority:Urgent

#1167 Allow generalized eigensolver to re-use pre-factorized matrix
  include/dlaf/eigensolver/gen_eigensolver.h
  include/dlaf/eigensolver/gen_eigensolver/api.h
  include/dlaf/eigensolver/gen_eigensolver/impl.h
  include/dlaf/eigensolver/gen_to_std.h
  include/dlaf_c/eigensolver/gen_eigensolver.h
  src/c_api/eigensolver/gen_eigensolver.cpp
  src/c_api/eigensolver/gen_eigensolver.h
  test/unit/c_api/eigensolver/CMakeLists.txt
  test/unit/c_api/eigensolver/test_gen_eigensolver_c_api.cpp
  test/unit/c_api/eigensolver/test_gen_eigensolver_c_api_wrapper.c
  test/unit/c_api/eigensolver/test_gen_eigensolver_c_api_wrapper.h
  test/unit/eigensolver/test_gen_eigensolver.cpp
Labels: Priority:Medium

#1166 Fix precompiled headers build
  ci/docker/debug-cuda-scalapack.yaml
  spack/packages/dla-future/package.py
  src/dummy.cpp
Labels: Priority:Low, Type:Problem

#1118 TriSolver (dist): move sorting permutation from CPU to GPU
  include/dlaf/eigensolver/tridiag_solver/impl.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/permutations/general.h
  include/dlaf/permutations/general/impl.h
  test/unit/permutations/test_permutations_distributed.cpp
Labels: Type:New Feature, Priority:High, Type:Optimization

#1171 Improve release script
  scripts/roll_release.sh
Labels: Priority:Medium, Type:Release

#1172 Update spack package post v0.6.0 release
  spack/packages/dla-future/package.py
Labels: Priority:Medium, Type:Release
