Repository eth-cscs/DLA-Future, pull requests merged in 2025-04, with the labels that each got.

#1312 bug fix: HDF5 test should wait before cleaning up
  test/unit/matrix/test_matrix_hdf5.cpp
Labels: Priority:Low, Type:Test issue

#1304 ReductionToBand, BTReductionToBand, TFactor: Taus on GPU
  include/dlaf/eigensolver/bt_reduction_to_band.h
  include/dlaf/eigensolver/bt_reduction_to_band/api.h
  include/dlaf/eigensolver/bt_reduction_to_band/impl.h
  include/dlaf/eigensolver/reduction_to_band.h
  include/dlaf/eigensolver/reduction_to_band/api.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
  include/dlaf/factorization/qr.h
  include/dlaf/factorization/qr/api.h
  include/dlaf/factorization/qr/t_factor_impl.h
  miniapp/miniapp_bt_reduction_to_band.cpp
  test/unit/eigensolver/test_bt_reduction_to_band.cpp
  test/unit/eigensolver/test_reduction_to_band.cpp
  test/unit/factorization/test_compute_t_factor.cpp
Labels: Type:Optimization, Type:Cleanup

#1315 Fix ctest error propagation in CI.
  ci/mpi-ctest
Labels: Type:Bug, Priority:Urgent, Category:CI

#1313 CI on beverin
  ci/.gitlab-ci.yml
  ci/base-images/amdgpu-cray-mpich/HOWTO.md
  ci/base-images/amdgpu-cray-mpich/build.Dockerfile
  ci/ci-ext-custom.yml
  ci/common-ci.yml
  ci/ctest_to_gitlab.sh
  ci/docker/codecov.Dockerfile
  ci/docker/common-amdgpu.yaml
  ci/docker/deploy.Dockerfile
  ci/docker/release-rocm602.yaml
  ci/mpi-ctest
  ci/rocm/clang15_release.yml
  ci/rocm/gcc12_release.yml
  ci/rocm/test.yml
  include/dlaf/matrix/copy_tile.h
Labels: Type:New Feature, Category:CI, Priority:High
