Repository eth-cscs/DLA-Future, pull requests merged in 2025-02, with the labels that each got.

#1214 TFactor: bulkerify GEMV (both MC and GPU)
  include/dlaf/eigensolver/bt_reduction_to_band/impl.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
  include/dlaf/factorization/qr.h
  include/dlaf/factorization/qr/api.h
  include/dlaf/factorization/qr/internal/get_tfactor_barrier_busy_wait.h
  include/dlaf/factorization/qr/internal/get_tfactor_num_workers.h
  include/dlaf/factorization/qr/t_factor_impl.h
  include/dlaf/lapack/tile.h
  include/dlaf/tune.h
  src/init.cpp
  src/tune.cpp
  test/unit/factorization/test_compute_t_factor.cpp
Labels: Type:Optimization

#1280 re-enable hdf5 test
  ci/ctest_to_gitlab.sh
  ci/docker/debug-cuda-gh200-scalapack.yaml
Labels: Category:CI, Priority:High

#1256 TFactor: use optimised kernel
  include/dlaf/factorization/qr/t_factor_impl.h
Labels: Type:Optimization

#1283 bug fix: eigensolvers miniapps check
  miniapp/miniapp_eigensolver.cpp
  miniapp/miniapp_gen_eigensolver.cpp
Labels: Type:Bug

#1270 Rename parameters from "nworkers" to "num-threads"
  include/dlaf/eigensolver/internal/get_red2band_panel_nworkers.h
  include/dlaf/eigensolver/internal/get_tridiag_rank1_nworkers.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
  include/dlaf/eigensolver/tridiag_solver/merge.h
  include/dlaf/tune.h
  src/init.cpp
  src/tune.cpp
Labels: Type:Cleanup

#1289 Avoid buffering in CI output.
  ci/ctest_to_gitlab.sh
Labels: Category:CI, Type:Problem

#1291 Update rocm pipeline to speed up CI
  ci/.gitlab-ci.yml
  ci/docker/release-rocm602.yaml
  ci/rocm/clang14_release.yml
  ci/rocm/clang15_release.yml
Labels: Category:CI, Priority:High, Type:Optimization

#1254 benchmark scripts: basic separation for alps vcluster, number of cores, gpu defaults, ...
  miniapp/miniapp_bt_reduction_to_band.cpp
  scripts/systems.py
Labels: Priority:Low

#1297 disable MPICH_GPU_SUPPORT_ENABLED where not needed
  ci/cuda/gcc13_debug.yml
  ci/cuda/gcc13_debug_scalapack.yml
  ci/cuda/gcc13_release_scalapack.yml
  ci/cuda/gcc13_release_stdexec.yml
Labels: Priority:Urgent

#1296 Preparation for v0.8.0 release
  CHANGELOG.md
  CITATION.cff
  CMakeLists.txt
  DOCUMENTATION.md
  README.md
  scripts/roll_release.sh
Labels: Priority:High, Type:Release
