Repository eth-cscs/DLA-Future, pull requests merged in 2025-03, with the labels that each got.

#1306 Link Testing to /dev/shm
  ci/mpi-ctest
Labels: Type:Bug, Priority:Urgent, Category:CI

#1299 Remove slow rocm 5.3.3 CI
  ci/.gitlab-ci.yml
  ci/docker/release-rocm533-stdexec.yaml
  ci/rocm/clang14_release_stdexec.yml
Labels: Category:CI, Priority:Medium

#1307 GTest update: revert erroneous removal of git reset for gtest patch application
  external/CMakeLists.txt
Labels: Priority:High, Type:Problem
