Repository eth-cscs/DLA-Future, pull requests merged in 2025-05, with the labels that each got.

#1325 Improve broadcast transposed
  include/dlaf/communication/broadcast_panel.h
  include/dlaf/eigensolver/gen_to_std/impl.h
  include/dlaf/eigensolver/reduction_to_band/impl.h
  include/dlaf/factorization/cholesky/impl.h
  test/unit/communication/test_broadcast_panel.cpp
Labels: Type:New Feature, Priority:High

#1327 Remove redundant CAPI tests.
  include/dlaf/memory/memory_chunk.h
  include/dlaf/memory/memory_type.h
  include/dlaf_c/eigensolver/eigensolver.h
  include/dlaf_c/eigensolver/gen_eigensolver.h
  include/dlaf_c/factorization/cholesky.h
  src/lapack/gpu/lacpy.cu
  test/unit/c_api/eigensolver/test_eigensolver_c_api.cpp
  test/unit/c_api/eigensolver/test_gen_eigensolver_c_api.cpp
  test/unit/c_api/factorization/test_cholesky_c_api.cpp
Labels: Priority:Medium, Type:Problem, Type:Test issue

#1326 Add potri c_api
  README.md
  include/dlaf_c/inverse/cholesky.h
  src/CMakeLists.txt
  src/c_api/inverse/cholesky.cpp
  src/c_api/inverse/cholesky.h
  test/unit/CMakeLists.txt
  test/unit/c_api/inverse/CMakeLists.txt
  test/unit/c_api/inverse/test_inverse_from_cholesky_factor_c_api.cpp
  test/unit/c_api/inverse/test_inverse_from_cholesky_factor_c_api_wrapper.c
  test/unit/c_api/inverse/test_inverse_from_cholesky_factor_c_api_wrapper.h
Labels: Type:New Feature, Priority:Medium

#1329 Prepare v0.10 release
  CHANGELOG.md
  CITATION.cff
  CMakeLists.txt
  DOCUMENTATION.md
  README.md
Labels: Priority:High, Type:Release

#1332 Fix CMake default CMAKE_CUDA_ARCHITECTURES warning
  CMakeLists.txt
Labels: Priority:Low
